services:
  dev-postgres:
    image: postgres:16-alpine
    container_name: blogslist-dev-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogslist
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    networks:
      - dev-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  dev-server:
    depends_on:
      dev-postgres:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    image: blogslist-dev-server
    container_name: blogslist-dev-server
    networks:
      - dev-network
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    environment:
      POSTGRES_URI: postgres://admin:admin@dev-postgres:5432/blogslist
      PORT: 3001
      SECRET: secret
      DATABASE_SSL: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  dev-client:
    depends_on:
      dev-server:
        condition: service_healthy
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    image: blogslist-dev-client
    container_name: blogslist-dev-client
    networks:
      - dev-network
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  dev-nginx:
    depends_on:
      dev-server:
        condition: service_healthy
      dev-client:
        condition: service_healthy
    image: nginx:stable-alpine
    container_name: blogslist-dev-nginx
    ports:
      - 8000:80
    networks:
      - dev-network
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

networks:
  dev-network:
    driver: bridge
