server {
  listen 80;

  # Proxy the Vite server
  location / {
    proxy_pass http://dev-client:5173;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Proxy API requests to the Express server
  location /api/ {
    proxy_pass http://dev-server:3001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}